### ISSUE TITLE
Support for overriding HTTP host and scheme

### ISSUE THREAD

**Issue by MrHash** [honeylex/honeylex#37]
Currently SERVER_HOST environment variable is used but might be better to use proxy forwarded headers, override HTTP_HOST or another technique which is more generic.

**Comment by MrHash** [comment]
`X-Forward-*` headers need to be passed on from proxy to backend & Symfony expects explicit trusted proxy ip configuration to override host and scheme. Meanwhile custom proxy headers are broken in https://github.com/blacklabelops/nginx/issues ...

**Comment by blacklabelops** [comment]
Can you please give a concrete example for the SERVER_HOST and HTTP_HOST solution? Which header field should be set with which nginx variable?

**Comment by MrHash** [comment]
Backend generates urls based on `X-Forwarded-*` headers so in normal cases this is fine. If the forwarded host is for example `api.honeylex.com` then urls generated (in emails etc.) do not reference the UI front end at `honeylex.com`. So overriding the host is necessary in a *web* context in this case. In a *console* context the host is specified explicitly from an environment var since there are no server variables.

**Comment by MrHash** [comment]
ref 5b66de196d27f354b8364c782399df0bb488b972 - expects updated build of proxy container
